// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: content.sql

package sqlc

import (
	"context"
)

const getContentByKey = `-- name: GetContentByKey :one
SELECT id, section_key, content, created_at, updated_at FROM content_blocks
WHERE section_key = $1 LIMIT 1
`

func (q *Queries) GetContentByKey(ctx context.Context, sectionKey string) (ContentBlock, error) {
	row := q.db.QueryRow(ctx, getContentByKey, sectionKey)
	var i ContentBlock
	err := row.Scan(
		&i.ID,
		&i.SectionKey,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContent = `-- name: UpsertContent :one
INSERT INTO content_blocks (section_key, content, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (section_key)
DO UPDATE SET content = $2, updated_at = NOW()
RETURNING id, section_key, content, created_at, updated_at
`

type UpsertContentParams struct {
	SectionKey string `json:"section_key"`
	Content    []byte `json:"content"`
}

func (q *Queries) UpsertContent(ctx context.Context, arg UpsertContentParams) (ContentBlock, error) {
	row := q.db.QueryRow(ctx, upsertContent, arg.SectionKey, arg.Content)
	var i ContentBlock
	err := row.Scan(
		&i.ID,
		&i.SectionKey,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
