// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerLTV = `-- name: GetCustomerLTV :many
SELECT u.id, u.first_name, u.last_name, u.email, COUNT(o.id) as total_orders, SUM(o.total_amount) as lifetime_value
FROM users u
JOIN orders o ON o.user_id = u.id
WHERE o.status = 'delivered'
GROUP BY u.id, u.first_name, u.last_name, u.email
ORDER BY lifetime_value DESC
LIMIT 50
`

type GetCustomerLTVRow struct {
	ID            pgtype.UUID `json:"id"`
	FirstName     *string     `json:"first_name"`
	LastName      *string     `json:"last_name"`
	Email         string      `json:"email"`
	TotalOrders   int64       `json:"total_orders"`
	LifetimeValue int64       `json:"lifetime_value"`
}

func (q *Queries) GetCustomerLTV(ctx context.Context) ([]GetCustomerLTVRow, error) {
	rows, err := q.db.Query(ctx, getCustomerLTV)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomerLTVRow{}
	for rows.Next() {
		var i GetCustomerLTVRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.TotalOrders,
			&i.LifetimeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLowStockProducts = `-- name: GetLowStockProducts :many
SELECT id, name, sku, stock, stock_status 
FROM products 
WHERE stock <= low_stock_threshold AND is_active = true
ORDER BY stock ASC
LIMIT 50
`

type GetLowStockProductsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Sku         string      `json:"sku"`
	Stock       int32       `json:"stock"`
	StockStatus *string     `json:"stock_status"`
}

func (q *Queries) GetLowStockProducts(ctx context.Context) ([]GetLowStockProductsRow, error) {
	rows, err := q.db.Query(ctx, getLowStockProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLowStockProductsRow{}
	for rows.Next() {
		var i GetLowStockProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Stock,
			&i.StockStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSellingProducts = `-- name: GetTopSellingProducts :many
SELECT p.id, p.name, p.sku, SUM(oi.quantity) as total_sold, SUM(oi.subtotal) as total_revenue
FROM order_items oi
JOIN products p ON p.id = oi.product_id
JOIN orders o ON o.id = oi.order_id
WHERE o.created_at >= $1
GROUP BY p.id, p.name, p.sku
ORDER BY total_sold DESC
LIMIT 10
`

type GetTopSellingProductsRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Sku          string      `json:"sku"`
	TotalSold    int64       `json:"total_sold"`
	TotalRevenue int64       `json:"total_revenue"`
}

func (q *Queries) GetTopSellingProducts(ctx context.Context, createdAt pgtype.Timestamp) ([]GetTopSellingProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopSellingProducts, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopSellingProductsRow{}
	for rows.Next() {
		var i GetTopSellingProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.TotalSold,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
