// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	Label        *string          `json:"label"`
	ContactEmail *string          `json:"contact_email"`
	Phone        *string          `json:"phone"`
	FirstName    *string          `json:"first_name"`
	LastName     *string          `json:"last_name"`
	DeliveryZone *string          `json:"delivery_zone"`
	Division     *string          `json:"division"`
	District     *string          `json:"district"`
	Thana        *string          `json:"thana"`
	AddressLine  *string          `json:"address_line"`
	Landmark     *string          `json:"landmark"`
	PostalCode   *string          `json:"postal_code"`
	IsDefault    bool             `json:"is_default"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Cart struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CartItem struct {
	ID        pgtype.UUID `json:"id"`
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
	VariantID pgtype.UUID `json:"variant_id"`
	Quantity  int32       `json:"quantity"`
}

type Category struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	ParentID        pgtype.UUID `json:"parent_id"`
	OrderIndex      int32       `json:"order_index"`
	Icon            *string     `json:"icon"`
	Image           *string     `json:"image"`
	IsActive        bool        `json:"is_active"`
	ShowInNav       bool        `json:"show_in_nav"`
	MetaTitle       *string     `json:"meta_title"`
	MetaDescription *string     `json:"meta_description"`
	Keywords        *string     `json:"keywords"`
}

type Collection struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Description *string          `json:"description"`
	Image       *string          `json:"image"`
	Story       *string          `json:"story"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type InventoryLog struct {
	ID           int32            `json:"id"`
	ProductID    pgtype.UUID      `json:"product_id"`
	VariantID    pgtype.UUID      `json:"variant_id"`
	ChangeAmount int32            `json:"change_amount"`
	Reason       string           `json:"reason"`
	ReferenceID  string           `json:"reference_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Status          string           `json:"status"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	ShippingAddress []byte           `json:"shipping_address"`
	PaymentMethod   *string          `json:"payment_method"`
	PaymentStatus   *string          `json:"payment_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	ID        pgtype.UUID    `json:"id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	VariantID pgtype.UUID    `json:"variant_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

type Product struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	Slug              string           `json:"slug"`
	Sku               string           `json:"sku"`
	Description       *string          `json:"description"`
	BasePrice         pgtype.Numeric   `json:"base_price"`
	SalePrice         pgtype.Numeric   `json:"sale_price"`
	Stock             int32            `json:"stock"`
	StockStatus       *string          `json:"stock_status"`
	LowStockThreshold int32            `json:"low_stock_threshold"`
	IsFeatured        bool             `json:"is_featured"`
	IsActive          bool             `json:"is_active"`
	Media             []byte           `json:"media"`
	Attributes        []byte           `json:"attributes"`
	Specifications    []byte           `json:"specifications"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type ProductCategory struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type ProductCollection struct {
	ProductID    pgtype.UUID `json:"product_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

type RefreshToken struct {
	ID        pgtype.UUID      `json:"id"`
	Token     string           `json:"token"`
	UserID    pgtype.UUID      `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Revoked   bool             `json:"revoked"`
	Device    *string          `json:"device"`
}

type Review struct {
	ID        pgtype.UUID      `json:"id"`
	ProductID pgtype.UUID      `json:"product_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Rating    int32            `json:"rating"`
	Comment   *string          `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
	Avatar    *string          `json:"avatar"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Variant struct {
	ID        pgtype.UUID `json:"id"`
	ProductID pgtype.UUID `json:"product_id"`
	Name      string      `json:"name"`
	Stock     int32       `json:"stock"`
	Sku       *string     `json:"sku"`
}
