// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atomicRemoveCartItem = `-- name: AtomicRemoveCartItem :exec
DELETE FROM cart_items ci
USING carts c
WHERE ci.cart_id = c.id
  AND c.user_id = $1
  AND ci.product_id = $2
`

type AtomicRemoveCartItemParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) AtomicRemoveCartItem(ctx context.Context, arg AtomicRemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, atomicRemoveCartItem, arg.UserID, arg.ProductID)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*) FROM orders WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountOrders(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id) VALUES ($1) RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, total_amount, shipping_address, payment_method, payment_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, status, total_amount, shipping_address, payment_method, payment_status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	Status          string         `json:"status"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	ShippingAddress []byte         `json:"shipping_address"`
	PaymentMethod   *string        `json:"payment_method"`
	PaymentStatus   *string        `json:"payment_status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.TotalAmount,
		arg.ShippingAddress,
		arg.PaymentMethod,
		arg.PaymentStatus,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingAddress,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, variant_id, quantity, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, variant_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	VariantID pgtype.UUID    `json:"variant_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT o.id, o.user_id, o.status, o.total_amount, o.shipping_address, o.payment_method, o.payment_status, o.created_at, o.updated_at, u.email, u.first_name, u.last_name
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE ($1::text = '' OR o.status = $1)
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllOrdersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetAllOrdersRow struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Status          string           `json:"status"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	ShippingAddress []byte           `json:"shipping_address"`
	PaymentMethod   *string          `json:"payment_method"`
	PaymentStatus   *string          `json:"payment_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	Email           string           `json:"email"`
	FirstName       *string          `json:"first_name"`
	LastName        *string          `json:"last_name"`
}

func (q *Queries) GetAllOrders(ctx context.Context, arg GetAllOrdersParams) ([]GetAllOrdersRow, error) {
	rows, err := q.db.Query(ctx, getAllOrders, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllOrdersRow{}
	for rows.Next() {
		var i GetAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.ShippingAddress,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at, updated_at FROM carts WHERE user_id = $1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByProductID = `-- name: GetCartItemByProductID :one
SELECT id, cart_id, product_id, variant_id, quantity FROM cart_items WHERE cart_id = $1 AND product_id = $2
`

type GetCartItemByProductIDParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) GetCartItemByProductID(ctx context.Context, arg GetCartItemByProductIDParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByProductID, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.variant_id, ci.quantity, p.name, p.slug, p.base_price, p.sale_price, p.media, v.stock, v.sku
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
JOIN variants v ON v.id = ci.variant_id
WHERE ci.cart_id = $1
`

type GetCartItemsRow struct {
	ID        pgtype.UUID    `json:"id"`
	CartID    pgtype.UUID    `json:"cart_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	VariantID pgtype.UUID    `json:"variant_id"`
	Quantity  int32          `json:"quantity"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	BasePrice pgtype.Numeric `json:"base_price"`
	SalePrice pgtype.Numeric `json:"sale_price"`
	Media     []byte         `json:"media"`
	Stock     int32          `json:"stock"`
	Sku       *string        `json:"sku"`
}

func (q *Queries) GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsRow{}
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.Name,
			&i.Slug,
			&i.BasePrice,
			&i.SalePrice,
			&i.Media,
			&i.Stock,
			&i.Sku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartWithItems = `-- name: GetCartWithItems :many
SELECT 
    c.id as cart_id,
    c.user_id,
    ci.id as item_id,
    ci.product_id,
    ci.variant_id,
    ci.quantity,
    p.name,
    p.slug,
    p.base_price,
    p.sale_price,
    p.media,
    v.stock,
    v.sku as variant_sku
FROM carts c
LEFT JOIN cart_items ci ON c.id = ci.cart_id
LEFT JOIN products p ON ci.product_id = p.id
LEFT JOIN variants v ON ci.variant_id = v.id
WHERE c.user_id = $1
`

type GetCartWithItemsRow struct {
	CartID     pgtype.UUID    `json:"cart_id"`
	UserID     pgtype.UUID    `json:"user_id"`
	ItemID     pgtype.UUID    `json:"item_id"`
	ProductID  pgtype.UUID    `json:"product_id"`
	VariantID  pgtype.UUID    `json:"variant_id"`
	Quantity   *int32         `json:"quantity"`
	Name       *string        `json:"name"`
	Slug       *string        `json:"slug"`
	BasePrice  pgtype.Numeric `json:"base_price"`
	SalePrice  pgtype.Numeric `json:"sale_price"`
	Media      []byte         `json:"media"`
	Stock      *int32         `json:"stock"`
	VariantSku *string        `json:"variant_sku"`
}

func (q *Queries) GetCartWithItems(ctx context.Context, userID pgtype.UUID) ([]GetCartWithItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartWithItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartWithItemsRow{}
	for rows.Next() {
		var i GetCartWithItemsRow
		if err := rows.Scan(
			&i.CartID,
			&i.UserID,
			&i.ItemID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.Name,
			&i.Slug,
			&i.BasePrice,
			&i.SalePrice,
			&i.Media,
			&i.Stock,
			&i.VariantSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, total_amount, shipping_address, payment_method, payment_status, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingAddress,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.variant_id, oi.quantity, oi.price, p.name, p.slug, p.media
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID        pgtype.UUID    `json:"id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	VariantID pgtype.UUID    `json:"variant_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Media     []byte         `json:"media"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsRow{}
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.Price,
			&i.Name,
			&i.Slug,
			&i.Media,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, user_id, status, total_amount, shipping_address, payment_method, payment_status, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.ShippingAddress,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPurchasedProduct = `-- name: HasPurchasedProduct :one
SELECT EXISTS (
    SELECT 1
    FROM order_items oi
    JOIN orders o ON o.id = oi.order_id
    WHERE o.user_id = $1 
      AND oi.product_id = $2
      AND o.status = 'delivered'
)
`

type HasPurchasedProductParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) HasPurchasedProduct(ctx context.Context, arg HasPurchasedProductParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPurchasedProduct, arg.UserID, arg.ProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const upsertCartItemAtomic = `-- name: UpsertCartItemAtomic :many
WITH 
  user_cart AS (
    SELECT id FROM carts WHERE user_id = $1
  ),
  stock_valid AS (
    SELECT v.id FROM variants v
    JOIN products p ON p.id = v.product_id
    WHERE v.id = $2
      AND v.stock >= $3
      AND p.is_active = TRUE
  ),
  existing_item AS (
    SELECT ci.id FROM cart_items ci
    JOIN user_cart uc ON ci.cart_id = uc.id
    WHERE ci.product_id = $4
      AND (ci.variant_id IS NOT DISTINCT FROM $2)
  ),
  updated AS (
    UPDATE cart_items SET quantity = $3
    WHERE id = (SELECT id FROM existing_item)
    RETURNING cart_id
  ),
  inserted AS (
    INSERT INTO cart_items (cart_id, product_id, variant_id, quantity)
    SELECT uc.id, $4, $2, $3
    FROM user_cart uc
    CROSS JOIN stock_valid sv
    WHERE NOT EXISTS (SELECT 1 FROM existing_item)
    RETURNING cart_id
  ),
  affected_cart AS (
    SELECT cart_id FROM updated
    UNION ALL
    SELECT cart_id FROM inserted
  )
SELECT ci.id, ci.cart_id, ci.product_id, ci.variant_id, ci.quantity,
       p.name, p.slug, p.base_price, p.sale_price, p.media, v.stock, v.sku as variant_sku
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
JOIN variants v ON v.id = ci.variant_id
WHERE ci.cart_id = (SELECT cart_id FROM affected_cart LIMIT 1)
`

type UpsertCartItemAtomicParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	VariantID pgtype.UUID `json:"variant_id"`
	Quantity  int32       `json:"quantity"`
	ProductID pgtype.UUID `json:"product_id"`
}

type UpsertCartItemAtomicRow struct {
	ID         pgtype.UUID    `json:"id"`
	CartID     pgtype.UUID    `json:"cart_id"`
	ProductID  pgtype.UUID    `json:"product_id"`
	VariantID  pgtype.UUID    `json:"variant_id"`
	Quantity   int32          `json:"quantity"`
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	BasePrice  pgtype.Numeric `json:"base_price"`
	SalePrice  pgtype.Numeric `json:"sale_price"`
	Media      []byte         `json:"media"`
	Stock      int32          `json:"stock"`
	VariantSku *string        `json:"variant_sku"`
}

// L9 FIX: Simplified atomic upsert without expression-based conflict target
func (q *Queries) UpsertCartItemAtomic(ctx context.Context, arg UpsertCartItemAtomicParams) ([]UpsertCartItemAtomicRow, error) {
	rows, err := q.db.Query(ctx, upsertCartItemAtomic,
		arg.UserID,
		arg.VariantID,
		arg.Quantity,
		arg.ProductID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpsertCartItemAtomicRow{}
	for rows.Next() {
		var i UpsertCartItemAtomicRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.Name,
			&i.Slug,
			&i.BasePrice,
			&i.SalePrice,
			&i.Media,
			&i.Stock,
			&i.VariantSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
