// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductCategory = `-- name: AddProductCategory :exec
INSERT INTO product_categories (product_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProductCategoryParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error {
	_, err := q.db.Exec(ctx, addProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const clearProductCategories = `-- name: ClearProductCategories :exec
DELETE FROM product_categories WHERE product_id = $1
`

func (q *Queries) ClearProductCategories(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearProductCategories, productID)
	return err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products 
WHERE ($1::boolean IS NULL OR is_active = $1)
AND ($2::boolean IS NULL OR is_featured = $2)
`

type CountProductsParams struct {
	IsActive   *bool `json:"is_active"`
	IsFeatured *bool `json:"is_featured"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.IsActive, arg.IsFeatured)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsWithCategoryFilter = `-- name: CountProductsWithCategoryFilter :one
SELECT COUNT(DISTINCT p.id) FROM products p
JOIN product_categories pc ON pc.product_id = p.id
JOIN categories c ON c.id = pc.category_id
WHERE c.slug = $1 AND ($2::boolean IS NULL OR p.is_active = $2)
`

type CountProductsWithCategoryFilterParams struct {
	Slug    string `json:"slug"`
	Column2 bool   `json:"column_2"`
}

func (q *Queries) CountProductsWithCategoryFilter(ctx context.Context, arg CountProductsWithCategoryFilterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsWithCategoryFilter, arg.Slug, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, meta_title, meta_description, meta_keywords, og_image)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, created_at, updated_at, search_vector, meta_title, meta_description, meta_keywords, og_image
`

type CreateProductParams struct {
	Name              string         `json:"name"`
	Slug              string         `json:"slug"`
	Sku               string         `json:"sku"`
	Description       *string        `json:"description"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	SalePrice         pgtype.Numeric `json:"sale_price"`
	Stock             int32          `json:"stock"`
	StockStatus       *string        `json:"stock_status"`
	LowStockThreshold int32          `json:"low_stock_threshold"`
	IsFeatured        bool           `json:"is_featured"`
	IsActive          bool           `json:"is_active"`
	Media             []byte         `json:"media"`
	Attributes        []byte         `json:"attributes"`
	Specifications    []byte         `json:"specifications"`
	MetaTitle         *string        `json:"meta_title"`
	MetaDescription   *string        `json:"meta_description"`
	MetaKeywords      *string        `json:"meta_keywords"`
	OgImage           *string        `json:"og_image"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Sku,
		arg.Description,
		arg.BasePrice,
		arg.SalePrice,
		arg.Stock,
		arg.StockStatus,
		arg.LowStockThreshold,
		arg.IsFeatured,
		arg.IsActive,
		arg.Media,
		arg.Attributes,
		arg.Specifications,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.OgImage,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Description,
		&i.BasePrice,
		&i.SalePrice,
		&i.Stock,
		&i.StockStatus,
		&i.LowStockThreshold,
		&i.IsFeatured,
		&i.IsActive,
		&i.Media,
		&i.Attributes,
		&i.Specifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getCategoryIDsForProduct = `-- name: GetCategoryIDsForProduct :many
SELECT category_id FROM product_categories WHERE product_id = $1
`

func (q *Queries) GetCategoryIDsForProduct(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getCategoryIDsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, created_at, updated_at, search_vector, meta_title, meta_description, meta_keywords, og_image FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Description,
		&i.BasePrice,
		&i.SalePrice,
		&i.Stock,
		&i.StockStatus,
		&i.LowStockThreshold,
		&i.IsFeatured,
		&i.IsActive,
		&i.Media,
		&i.Attributes,
		&i.Specifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, created_at, updated_at, search_vector, meta_title, meta_description, meta_keywords, og_image FROM products WHERE sku = $1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Description,
		&i.BasePrice,
		&i.SalePrice,
		&i.Stock,
		&i.StockStatus,
		&i.LowStockThreshold,
		&i.IsFeatured,
		&i.IsActive,
		&i.Media,
		&i.Attributes,
		&i.Specifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, created_at, updated_at, search_vector, meta_title, meta_description, meta_keywords, og_image FROM products WHERE slug = $1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Description,
		&i.BasePrice,
		&i.SalePrice,
		&i.Stock,
		&i.StockStatus,
		&i.LowStockThreshold,
		&i.IsFeatured,
		&i.IsActive,
		&i.Media,
		&i.Attributes,
		&i.Specifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, created_at, updated_at, search_vector, meta_title, meta_description, meta_keywords, og_image FROM products 
WHERE ($3::boolean IS NULL OR is_active = $3)
AND ($4::boolean IS NULL OR is_featured = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetProductsParams struct {
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
	IsActive   *bool `json:"is_active"`
	IsFeatured *bool `json:"is_featured"`
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProducts,
		arg.Limit,
		arg.Offset,
		arg.IsActive,
		arg.IsFeatured,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Description,
			&i.BasePrice,
			&i.SalePrice,
			&i.Stock,
			&i.StockStatus,
			&i.LowStockThreshold,
			&i.IsFeatured,
			&i.IsActive,
			&i.Media,
			&i.Attributes,
			&i.Specifications,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForCollection = `-- name: GetProductsForCollection :many
SELECT p.id, p.name, p.slug, p.sku, p.description, p.base_price, p.sale_price, p.stock, p.stock_status, p.low_stock_threshold, p.is_featured, p.is_active, p.media, p.attributes, p.specifications, p.created_at, p.updated_at, p.search_vector, p.meta_title, p.meta_description, p.meta_keywords, p.og_image FROM products p
JOIN product_collections pc ON pc.product_id = p.id
WHERE pc.collection_id = $1 AND p.is_active = true
ORDER BY p.created_at DESC
`

func (q *Queries) GetProductsForCollection(ctx context.Context, collectionID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsForCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Description,
			&i.BasePrice,
			&i.SalePrice,
			&i.Stock,
			&i.StockStatus,
			&i.LowStockThreshold,
			&i.IsFeatured,
			&i.IsActive,
			&i.Media,
			&i.Attributes,
			&i.Specifications,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithCategoryFilter = `-- name: GetProductsWithCategoryFilter :many
SELECT DISTINCT p.id, p.name, p.slug, p.sku, p.description, p.base_price, p.sale_price, p.stock, p.stock_status, p.low_stock_threshold, p.is_featured, p.is_active, p.media, p.attributes, p.specifications, p.created_at, p.updated_at, p.search_vector, p.meta_title, p.meta_description, p.meta_keywords, p.og_image FROM products p
JOIN product_categories pc ON pc.product_id = p.id
JOIN categories c ON c.id = pc.category_id
WHERE c.slug = $1 AND ($2::boolean IS NULL OR p.is_active = $2)
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type GetProductsWithCategoryFilterParams struct {
	Slug    string `json:"slug"`
	Column2 bool   `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetProductsWithCategoryFilter(ctx context.Context, arg GetProductsWithCategoryFilterParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsWithCategoryFilter,
		arg.Slug,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Description,
			&i.BasePrice,
			&i.SalePrice,
			&i.Stock,
			&i.StockStatus,
			&i.LowStockThreshold,
			&i.IsFeatured,
			&i.IsActive,
			&i.Media,
			&i.Attributes,
			&i.Specifications,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithPriceRange = `-- name: GetProductsWithPriceRange :many
SELECT id, name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, created_at, updated_at, search_vector, meta_title, meta_description, meta_keywords, og_image FROM products
WHERE base_price >= $1 AND base_price <= $2 AND ($3::boolean IS NULL OR is_active = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type GetProductsWithPriceRangeParams struct {
	BasePrice   pgtype.Numeric `json:"base_price"`
	BasePrice_2 pgtype.Numeric `json:"base_price_2"`
	Column3     bool           `json:"column_3"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
}

func (q *Queries) GetProductsWithPriceRange(ctx context.Context, arg GetProductsWithPriceRangeParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsWithPriceRange,
		arg.BasePrice,
		arg.BasePrice_2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Description,
			&i.BasePrice,
			&i.SalePrice,
			&i.Stock,
			&i.StockStatus,
			&i.LowStockThreshold,
			&i.IsFeatured,
			&i.IsActive,
			&i.Media,
			&i.Attributes,
			&i.Specifications,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.OgImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductCategory = `-- name: RemoveProductCategory :exec
DELETE FROM product_categories WHERE product_id = $1 AND category_id = $2
`

type RemoveProductCategoryParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) RemoveProductCategory(ctx context.Context, arg RemoveProductCategoryParams) error {
	_, err := q.db.Exec(ctx, removeProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, slug = $3, description = $4, base_price = $5, sale_price = $6, 
    stock = $7, stock_status = $8, low_stock_threshold = $9, is_featured = $10, 
    is_active = $11, media = $12, attributes = $13, specifications = $14,
    meta_title = $15, meta_description = $16, meta_keywords = $17, og_image = $18
WHERE id = $1
RETURNING id, name, slug, sku, description, base_price, sale_price, stock, stock_status, low_stock_threshold, is_featured, is_active, media, attributes, specifications, created_at, updated_at, search_vector, meta_title, meta_description, meta_keywords, og_image
`

type UpdateProductParams struct {
	ID                pgtype.UUID    `json:"id"`
	Name              string         `json:"name"`
	Slug              string         `json:"slug"`
	Description       *string        `json:"description"`
	BasePrice         pgtype.Numeric `json:"base_price"`
	SalePrice         pgtype.Numeric `json:"sale_price"`
	Stock             int32          `json:"stock"`
	StockStatus       *string        `json:"stock_status"`
	LowStockThreshold int32          `json:"low_stock_threshold"`
	IsFeatured        bool           `json:"is_featured"`
	IsActive          bool           `json:"is_active"`
	Media             []byte         `json:"media"`
	Attributes        []byte         `json:"attributes"`
	Specifications    []byte         `json:"specifications"`
	MetaTitle         *string        `json:"meta_title"`
	MetaDescription   *string        `json:"meta_description"`
	MetaKeywords      *string        `json:"meta_keywords"`
	OgImage           *string        `json:"og_image"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.BasePrice,
		arg.SalePrice,
		arg.Stock,
		arg.StockStatus,
		arg.LowStockThreshold,
		arg.IsFeatured,
		arg.IsActive,
		arg.Media,
		arg.Attributes,
		arg.Specifications,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
		arg.OgImage,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.Description,
		&i.BasePrice,
		&i.SalePrice,
		&i.Stock,
		&i.StockStatus,
		&i.LowStockThreshold,
		&i.IsFeatured,
		&i.IsActive,
		&i.Media,
		&i.Attributes,
		&i.Specifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.OgImage,
	)
	return i, err
}

const updateProductStatus = `-- name: UpdateProductStatus :exec
UPDATE products SET is_active = $2 WHERE id = $1
`

type UpdateProductStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) error {
	_, err := q.db.Exec(ctx, updateProductStatus, arg.ID, arg.IsActive)
	return err
}

const updateProductStock = `-- name: UpdateProductStock :execrows
UPDATE products SET stock = stock + $2 WHERE id = $1 AND stock + $2 >= 0
`

type UpdateProductStockParams struct {
	ID    pgtype.UUID `json:"id"`
	Stock int32       `json:"stock"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProductStock, arg.ID, arg.Stock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
