// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error
	AddProductToCollection(ctx context.Context, arg AddProductToCollectionParams) error
	AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) error
	AtomicRemoveCartItem(ctx context.Context, arg AtomicRemoveCartItemParams) error
	CheckItemInWishlist(ctx context.Context, arg CheckItemInWishlistParams) (bool, error)
	ClearCart(ctx context.Context, cartID pgtype.UUID) error
	ClearProductCategories(ctx context.Context, productID pgtype.UUID) error
	CountInventoryLogs(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountOrders(ctx context.Context, dollar_1 string) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountProductsWithCategoryFilter(ctx context.Context, arg CountProductsWithCategoryFilterParams) (int64, error)
	CountProductsWithSearch(ctx context.Context, arg CountProductsWithSearchParams) (int64, error)
	CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateInventoryLog(ctx context.Context, arg CreateInventoryLogParams) (InventoryLog, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error)
	CreateWishlist(ctx context.Context, userID pgtype.UUID) (Wishlist, error)
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteCollection(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteReview(ctx context.Context, id pgtype.UUID) error
	DeleteVariant(ctx context.Context, id pgtype.UUID) error
	DeleteVariantsByProductID(ctx context.Context, productID pgtype.UUID) error
	GetActiveChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	GetActiveCollections(ctx context.Context) ([]Collection, error)
	GetActiveNavCategories(ctx context.Context) ([]Category, error)
	GetAddressesByUserID(ctx context.Context, userID pgtype.UUID) ([]Address, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllCollections(ctx context.Context) ([]Collection, error)
	GetAllOrders(ctx context.Context, arg GetAllOrdersParams) ([]GetAllOrdersRow, error)
	GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error)
	GetCartItemByProductID(ctx context.Context, arg GetCartItemByProductIDParams) (CartItem, error)
	GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error)
	GetCartWithItems(ctx context.Context, userID pgtype.UUID) ([]GetCartWithItemsRow, error)
	GetCategoriesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Category, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCategoryIDsForProduct(ctx context.Context, productID pgtype.UUID) ([]pgtype.UUID, error)
	GetChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error)
	GetCollectionBySlug(ctx context.Context, slug string) (Collection, error)
	GetContentByKey(ctx context.Context, sectionKey string) (ContentBlock, error)
	GetInventoryLogs(ctx context.Context, arg GetInventoryLogsParams) ([]InventoryLog, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsRow, error)
	GetOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Order, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProductIDsForCollection(ctx context.Context, collectionID pgtype.UUID) ([]pgtype.UUID, error)
	GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error)
	GetProductsForCollection(ctx context.Context, collectionID pgtype.UUID) ([]Product, error)
	GetProductsWithCategoryFilter(ctx context.Context, arg GetProductsWithCategoryFilterParams) ([]Product, error)
	GetProductsWithPriceRange(ctx context.Context, arg GetProductsWithPriceRangeParams) ([]Product, error)
	GetProductsWithSearch(ctx context.Context, arg GetProductsWithSearchParams) ([]Product, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetReviewByID(ctx context.Context, id pgtype.UUID) (Review, error)
	GetReviewsByProductID(ctx context.Context, productID pgtype.UUID) ([]GetReviewsByProductIDRow, error)
	GetRootCategories(ctx context.Context) ([]Category, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserReviewForProduct(ctx context.Context, arg GetUserReviewForProductParams) (Review, error)
	GetVariantByID(ctx context.Context, id pgtype.UUID) (Variant, error)
	GetVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]Variant, error)
	GetWishlistByUserID(ctx context.Context, userID pgtype.UUID) (Wishlist, error)
	GetWishlistItems(ctx context.Context, wishlistID pgtype.UUID) ([]GetWishlistItemsRow, error)
	HasPurchasedProduct(ctx context.Context, arg HasPurchasedProductParams) (bool, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveProductCategory(ctx context.Context, arg RemoveProductCategoryParams) error
	RemoveProductFromCollection(ctx context.Context, arg RemoveProductFromCollectionParams) error
	RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) error
	RevokeRefreshToken(ctx context.Context, token string) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (RefreshToken, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryOrder(ctx context.Context, arg UpdateCategoryOrderParams) error
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) error
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error)
	UpsertCartItemAtomic(ctx context.Context, arg UpsertCartItemAtomicParams) ([]UpsertCartItemAtomicRow, error)
	UpsertContent(ctx context.Context, arg UpsertContentParams) (ContentBlock, error)
}

var _ Querier = (*Queries)(nil)
